CREATE DATABASE examonline;

GRANT ALL PRIVILEGES ON examonline.* TO 'examonline' IDENTIFIED BY 'passwd' WITH GRANT OPTION;

USE examonline;

Create table ADMIN_INFO (
ADMIN_USER_NAME char(15) PRIMARY KEY, 
ADMIN_PASSWORD char(10) NOT NULL,
ADMIN_IS_ROOT TINYINT(1) NOT NULL);

Create table TEST_RESULTS (
USER_NAME char(20) NOT NULL, 
TEST_CODE SMALLINT NOT NULL, 
TEST_SUBJECT_CODE TINYINT NOT NULL, 
TOTAL_QUESTIONS SMALLINT NOT NULL,
TOTAL_ATTEMPTED SMALLINT Not NULL,
TOTAL_SCORE decimal(4,2) NOT NULL, 
TOTAL_TIME_TAKEN SMALLINT NOT NULL);

Create table GLOBAL_PROPERTIES (
PROP_NAME char(20) PRIMARY KEY,
PROP_VALUE char(200) NOT NULL);

Create table USERS_INFO (
USER_NAME char(20) PRIMARY KEY, 
FIRST_NAME char(15) NOT NULL,
MIDDLE_NAME char(15) DEFAULT NULL,
LAST_NAME char(15) NOT NULL,
USER_PASSWORD char(10) NOT NULL,
ADDRESS char(50) NOT NULL, 
CITY char(20) NOT NULL, 
STATE char(20) NOT NULL,
COUNTRY char(20) NOT NULL, 
PIN MEDIUMINT NOT NULL, 
DATE_OF_BIRTH DATE NOT NULL, 
SEX TINYINT NOT NULL, 
PHONE BIGINT NOT NULL, 
EMAIL char(50) NOT NULL, 
PASSWORD_REMINDER_QUESTION TINYINT NOT NULL,
PASSWORD_REMINDER_ANSWER char(20) NOT NULL);

Create table TESTS_INFO (
TEST_CODE SMALLINT PRIMARY KEY, 
ADMIN_USER_NAME char(15) NOT NULL, 
TEST_NAME char(20) NOT NULL, 
TEST_CREATION_DATE DATE NOT NULL, 
TEST_LAST_UPDATION_DATE DATE NOT NULL, 
TEST_DURATION SMALLINT NOT NULL, 
TEST_CURRENT_STATUS TINYINT NOT NULL, 
TEST_NO_OF_SUBJECTS TINYINT NOT NULL, 
TEST_DESCRIPTION char(200));

Create table SUBJECTS_INFO(
TEST_CODE SMALLINT NOT NULL, 
SUBJECT_CODE SMALLINT NOT NULL,
SUBJECT_NAME char(25) NOT NULL, 
SUBJECT_NO_OF_QUESTIONS SMALLINT NOT NULL);

Create table QUESTIONS_TABLE(
QUESTION_ID int PRIMARY KEY,
TEST_CODE SMALLINT NOT NULL, 
SUBJECT_CODE SMALLINT NOT NULL,
QUESTION_DATA char(200) NOT NULL,
QUESTION_CHOICE_1 char(150) NOT NULL,
QUESTION_CHOICE_2 char(150) NOT NULL,
QUESTION_CHOICE_3 char(150) NOT NULL,
QUESTION_CHOICE_4 char(150) NOT NULL,
QUESTION_CORRECT_ANSWER SMALLINT NOT NULL);

Create table QUESTION_IMAGES(QUESTION_ID int NOT NULL,IMAGE_NAME char(15) NOT NULL,IMAGE_DATA BLOB NOT NULL);

insert into ADMIN_INFO values('examonline','passwd');
